# Generated by Django 4.2.5 on 2024-03-28 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dietetica', '0005_rename_productos_pormayor_productospormayor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedores',
            name='direccion',
        ),
    ]
