# Generated by Django 4.2.5 on 2024-03-28 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dietetica', '0006_remove_vendedores_direccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='cantidad',
            new_name='cantidad_en_gramos',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='precio',
            new_name='precio_en_pesos',
        ),
        migrations.RenameField(
            model_name='productospormayor',
            old_name='cantidad',
            new_name='cantidad_en_kg',
        ),
        migrations.RenameField(
            model_name='productospormayor',
            old_name='precio',
            new_name='precio_en_pesos',
        ),
    ]
